name: Build and Upload app to Firebase App Distribution(CI-CD)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

#      - name: Get Application version name
#        run: ./gradlew -q printVersionName
#        id: versionName
#
#      - name: Get Application version Code
#        run: ./gradlew -q printVersionCode
#        id: versionCode

      - name: Generate APK file
        #      Means if above task is status is success or not still this task will perform
        #      if: always()
        run: ./gradlew assembleDebug

      - name: Upload apk file to Firebase App Distributor
        #      Means if above task is status is success or not still this task will perform
        #      if: always()
        #     'uses:' is like dependency in build.gradle : it is integrate third party library and 'with:' is like we need this params for initialize libs.
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
#          tag_id: ${{steps.versionName}}
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          groups: cicd_tester
          file: app/build/outputs/apk/debug/app-debug.apk

#     It is save build file in artifacts.zip in Github Summery under Action
#    - name: Upload AAR files
#      if: always()
#      uses: actions/upload-artifact@v2
#      with:
#          name: artifacts.zip
#          path: |
#            app/build/outputs/apk/debug/app-debug.apk