name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Generate AAR and APK files
      if: always()
      run: ./gradlew assembleDebug

    - name: Upload apk file to Firebase App Distributor
      if: always()
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
        groups: cicd_tester
        file: app/build/outputs/apk/debug/app-debug.apk

#     It is save build file in artifacts.zip in Github Summery under Action
#    - name: Upload AAR files
#      if: always()
#      uses: actions/upload-artifact@v2
#      with:
#          name: artifacts.zip
#          path: |
#            app/build/outputs/apk/debug/app-debug.apk